repos:
-   repo: https://github.com/ambv/black
    rev: 22.1.0
    hooks:
    - id: black
      args: ["--config=pyproject.toml", "--check"]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
      args: ["--config=.flake8"]
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    - id: isort
